name: my_android_app
description: A new Flutter project.
version: 1.0.0+1  # â† âœ… è¿½åŠ ï¼ˆãƒãƒ¼ã‚¸ãƒ§ãƒ³å + ãƒ“ãƒ«ãƒ‰ç•ªå·ï¼‰
publish_to: 'none' # Flutter packages shouldn't be published

environment:
  sdk: '^3.7.0'  # SDKã®ãƒãƒ¼ã‚¸ãƒ§ãƒ³åˆ¶ç´„ã‚’è¿½åŠ 

dependencies:
  flutter:
    sdk: flutter


  # å¿…è¦ãªãƒ‘ãƒƒã‚±ãƒ¼ã‚¸ã‚’è¿½åŠ 
  csv: ^6.0.0  # æœ€æ–°ãƒãƒ¼ã‚¸ãƒ§ãƒ³ã«æ›´æ–°
  fl_chart: ^1.0.2
  timezone: ^0.9.4

  intl: ^0.20.2
  path_provider: ^2.0.15
  package_info_plus: ^4.0.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  # ğŸ”½ è¿½åŠ ï¼ˆãƒªã‚¹ãƒˆUIã®å±•é–‹ãƒ»ã‚¢ã‚¤ã‚³ãƒ³å¯¾å¿œãªã©ã«ä½¿ç”¨ï¼‰
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.10
  provider: ^6.0.0
  awesome_notifications: ^0.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/daily_insights.csv
    - assets/quotes.csv

    - assets/HappinessLevelDB1_v2.csv
